# Generated by Django 4.0.8 on 2023-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_alter_data_department_alter_department_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='cutoff_2022',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
